name: tag

on:
  push:
    tags:
      - '*'

jobs:
  goproxy:
    runs-on: ubuntu-latest
    container:
      image: golang:1.15-alpine3.11
    steps:
      - name: Resolve
        env:
          GOPROXY: https://proxy.golang.org
          GO111MODULE: on
        run: go get github.com/mjpitz/go-ga

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USERNAME}" --password-stdin
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Container Image
        run: |
          docker buildx build . \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg VERSION=${GITHUB_REF##*/v} \
            --tag mjpitz/beacon:latest \
            --tag mjpitz/beacon:${GITHUB_REF##*/v} \
            -f Dockerfile \
            --push
